#!/usr/bin/env python
"""
Server that takes an uploaded PNG and classifies
it based on a pre-trained Keras model.
"""
import numpy as np
import png
import os

from flask import Flask, request, abort, jsonify, redirect, url_for
from keras.models import load_model

app = Flask(__name__)

model = load_model('model.h5')
shape = model.layers[0].input.get_shape()
newshape = [x or 1 for x in shape.as_list()]

@app.route("/mnist/classify", methods=['POST', 'GET'])
def classify():
    try:
        if request.method == 'POST':
            fd = request.files['file']
            reader = png.Reader(fd)
            nr, nc, pngdata, meta = reader.asDirect()
            data = np.vstack(map(np.float32, pngdata)) / 255.
            data = data.reshape(newshape)
            pred = int(np.argmax(model.predict(data)[0]))
            return jsonify({"cls": pred, "fn": fd.filename})
    except png.FormatError as e:
        return abort(404)
    except Exception as e:
        return abort(404)
    return """
    <!doctype html>
    <style>h2,p {font-family: sans-serif;}</style>
    <title>Identify</title>
    <h2>Upload an image to identify</h2>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file><input type=submit value=Upload></p>
    </form>
    </html>
    """

@app.route('/', methods=['GET', 'POST'])
def index():
    return redirect(url_for('classify'))

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000, debug=False)
